# Macro file for sauna
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute gps.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 1
# 
# gamma 662 keV from (0,0,0) and isotropic angle distribution
#
/gps/particle gamma
/gps/ene/mono 662 keV
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/run/beamOn 100
