# Macro file for example sauna
# 
# To be run preferably in batch, without graphics:
# % examplesauna run2.mac
#
#/run/numberOfThreads 4
/run/initialize
#
/control/verbose 2
/run/verbose 2
#
# gamma 6 MeV to the direction (0.,0.,1.)
# 10000 events
#
/gps/particle gamma
/gps/energy 6 MeV
#
/run/printProgress 100
/run/beamOn 1000
# 
# proton 210 MeV to the direction (0.,0.,1.)
# 1000 events
#
/gps/particle proton
/gps/energy 210 MeV
#
/run/beamOn 1000
