# Macro file for sauna
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute test.mac
#
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 2
/tracking/verbose 1
#/tracking/storeTrajectory 1
# 
##########################
# MORE THAN ONE PARTICLE #
##########################
#
/gps/source/multiplevertex true
#
# electron and isotropic angle distribution
#
/gps/particle e-
/gps/ene/mono 300 keV
/gps/pos/centre 0 0. 0. mm
/gps/ang/type iso
#
#
/gps/source/add 1
#
/gps/particle e-
/gps/ene/mono 100 keV
/gps/pos/centre 0 0. 0. mm
/gps/ang/type iso
#
#
/gps/source/add 1
#
# gamma 662 keV and isotropic angle distribution
#
/gps/particle gamma
/gps/ene/mono 662 keV
/gps/pos/centre 0 0. 0. mm
/gps/ang/type iso
#
/run/beamOn 1000