# Macro file for sauna
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute cesium.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
#/vis/disable
/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 1
# 
################
# ONE PARTICLE #
################
# gamma 662 keV from (0,0,0) and isotropic angle distribution
#
/gps/particle e-
/gps/ene/mono 662 keV
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/run/beamOn 10
#
##########################
# MORE THAN ONE PARTICLE #
##########################
/gps/source/multiplevertex true
#
# gamma 662 keV and isotropic angle distribution
#
#/gps/particle gamma
#/gps/ene/mono 662 keV
#/gps/pos/centre 6.35 0. 0. mm
#/gps/ang/type iso
#
# electron and isotropic angle distribution
#
#/gps/source/add 1
#
#/gps/particle e-
#/gps/ene/mono 300 keV
#/gps/pos/centre 6.35 0. 0. mm
#/gps/ang/type iso
#
#/gps/source/list
#/run/beamOn 10