name: run

on:
    push:
        branches:
            - main

jobs:
    run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Build and run docker images
              run: make compile